### ISSUE TITLE
RPC tracking issue

### ISSUE THREAD

**Issue by rgarc** [category-labs/monad-bft#633]
Tentative list of RPC methods needed for metamask functionality.
- [x] https://github.com/monad-crypto/monad-bft/issues/572
- [x] https://github.com/monad-crypto/monad-bft/issues/573
- [x] https://github.com/monad-crypto/monad-bft/issues/574
- [x] https://github.com/monad-crypto/monad-bft/issues/575
- [x] https://github.com/monad-crypto/monad-bft/issues/576
- [x] https://github.com/monad-crypto/monad-bft/issues/577
- [x] https://github.com/monad-crypto/monad-bft/issues/578
- [x] https://github.com/monad-crypto/monad-bft/issues/579
- [x] https://github.com/monad-crypto/monad-bft/issues/580
- [x] https://github.com/monad-crypto/monad-bft/issues/581
- [x] https://github.com/monad-crypto/monad-bft/issues/582
- [x] https://github.com/monad-crypto/monad-bft/issues/583
- [x] https://github.com/monad-crypto/monad-bft/issues/584
- [x] https://github.com/monad-crypto/monad-bft/issues/585
- [x] https://github.com/monad-crypto/monad-bft/issues/586
- [x] https://github.com/monad-crypto/monad-bft/issues/587
- [x] https://github.com/monad-crypto/monad-bft/issues/588
- [x] https://github.com/monad-crypto/monad-bft/issues/589
- [x] https://github.com/monad-crypto/monad-bft/issues/590
- [x] https://github.com/monad-crypto/monad-bft/issues/591
- [x] https://github.com/monad-crypto/monad-bft/issues/592
- [x] https://github.com/monad-crypto/monad-bft/issues/593

- [x] https://github.com/monad-crypto/monad-bft/issues/602
- [x] https://github.com/monad-crypto/monad-bft/issues/603
- [x] https://github.com/monad-crypto/monad-bft/issues/604
- [x] https://github.com/monad-crypto/monad-bft/issues/605
- [x] https://github.com/monad-crypto/monad-bft/issues/606
- [x] https://github.com/monad-crypto/monad-bft/issues/607
- [ ] https://github.com/monad-crypto/monad-bft/issues/608
- [x] https://github.com/monad-crypto/monad-bft/issues/609
- [ ] https://github.com/monad-crypto/monad-bft/issues/610
- [ ] https://github.com/monad-crypto/monad-bft/issues/611
- [x] https://github.com/monad-crypto/monad-bft/issues/612
- [ ] https://github.com/monad-crypto/monad-bft/issues/613

- [ ] https://github.com/monad-crypto/monad-bft/issues/618
- [ ] https://github.com/monad-crypto/monad-bft/issues/619
- [ ] https://github.com/monad-crypto/monad-bft/issues/620

- [x] https://github.com/monad-crypto/monad-bft/issues/627
- [x] https://github.com/monad-crypto/monad-bft/issues/628
- [x] https://github.com/monad-crypto/monad-bft/issues/629
- [x] https://github.com/monad-crypto/monad-bft/issues/630
- [x] https://github.com/monad-crypto/monad-bft/issues/631
- [ ] https://github.com/monad-crypto/monad-bft/issues/632

**Comment by keone** [comment]
https://docs.google.com/spreadsheets/d/162ZN85o07sVP5VpxO1_tSVwGcdgzBvLSmEa_rg9Aslo/edit#gid=0
